version: '3'

services:
  app_instancia1:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: pos-facef/app1:v1.0.0
    ports:
      - "3001:3000"
    networks:
      - app-network
  
  app_instancia2:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: pos-facef/app1:v1.0.0
    ports:
      - "3002:3000"
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - app_instancia1
      - app_instancia2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge